/* ============================================================
   FAMILY MEAL — Datos base (semilla)
   Esta es tu información inicial. La app la copia al navegador la
   primera vez; después tus cambios viven en el navegador y en tus
   copias de respaldo. Puedes editar estas listas para cambiar los
   valores de fábrica (al "Restaurar datos de fábrica" se usan estos).
   ============================================================ */
window.FM_DATA = {

  ajustes: { moneda: '₡', familia: 'Familia', titular: 'Vero' },

  // ---------- familia ----------
  family: [
    { id:'vero', name:'Verónica', role:'Mamá · 29 años', age:29, weight:64, hMin:41, hMax:55, color:'#A32C54',
      portions:{ kcal:1700, protein:'120–130 g', carbs:'150–170 g', fat:'50–60 g', fiber:'25 g', fruit:'2 tazas', veg:'3 tazas', dairy:'2–3 tazas', water:'2.7 L' },
      likes:['Yoyo (huevo+plátano+queso)','Huevo','Carne','Pollo','Cerdo','Chuleta ahumada','Costillas','Queso','Frijoles','Lentejas','Arroz','Arepas','Yuca','Camote','Sancocho','Sopas','Sándwich completo','Wrap','Hamburguesa','Pepito','Mango','Melón','Mandarina','Papaya en jugo'], dislikes:[],
      needs:['Quiere aumentar masa muscular: priorizar proteína','Necesita más fibra y legumbres','Le cuesta tomar agua — meta 2.7 L/día','Come menos bajo estrés o estudiando','Prefiere comida casera'], body:{}, tipoCuerpo:'—' },
    { id:'papa', name:'Maykol', role:'Papá · 32 años', age:32, weight:174, hMin:56, hMax:76, color:'#14274E',
      portions:{ kcal:2400, protein:'140–170 g', proteinSplit:'Desayuno 35–40 g · Merienda 20 g · Almuerzo 40–45 g · Merienda 20 g · Cena 35–45 g', carbs:'300 g', fat:'80 g', fiber:'38 g', fruit:'2 tazas', veg:'3 tazas', dairy:'3 tazas', water:'3.7 L' },
      likes:['Carne','Pollo','Cerdo','Sopas','Sancocho','Sándwich completo','Pepito','Hamburguesa','Arroz','Comida tradicional casera'], dislikes:['Huevo como desayuno principal'],
      needs:['Cocina muy bien — suele preparar los almuerzos','Pierde el apetito cuando está enfermo','Peso por encima del rango: enfoque gradual y sostenible','Priorizar proteína magra, verduras y más agua'], body:{}, tipoCuerpo:'—' },
    { id:'taylor', name:'Taylor', role:'10 años', age:10, weight:49, hMin:25, hMax:45, color:'#C28A2A',
      portions:{ kcal:2000, protein:'40 g', carbs:'260 g', fat:'65 g', fiber:'26 g', fruit:'2 tazas', veg:'2.5 tazas', dairy:'3 tazas', water:'2.1 L' },
      likes:['Pasta con carne molida','Lentejas con arroz','Arroz con leche','Avena cocida','Arepa con queso','Arroz cantonés','Pollo agridulce','Sopas','Crema de ayote','Pollo guisado','Pizza','Lasaña','Mango','Mandarina','Fresas','Melón','Papa','Zanahoria','Maíz','Atún/sardina en salsa'],
      dislikes:['Lechuga','Tomate crudo','Pepino','Brócoli','Piña (le pica)','Atún simple'],
      needs:['Come más carbohidratos que proteína — equilibrar el plato','Peso sobre el rango: priorizar verduras','Acepta pescado solo cocido en salsa','Comida ideal: arroz cantonés + pollo agridulce'], body:{}, tipoCuerpo:'—' },
    { id:'emmeth', name:'Emmeth', role:'7 años', age:7, weight:23, hMin:20, hMax:32, color:'#0F7A63',
      portions:{ kcal:1700, protein:'34 g', carbs:'220 g', fat:'55 g', fiber:'25 g', fruit:'1.5 tazas', veg:'2 tazas', dairy:'2.5 tazas', water:'1.9 L' },
      likes:['Carne','Bistec','Pollo','Muslo de pollo','Chuleta','Cerdo','Jamón','Mortadela','Queso','Arroz blanco','Papa','Pasta','Pizza'],
      dislikes:['Cebolla visible','Culantro visible','Chile dulce visible','Cremas','Arroz con leche','Arroz con pollo','Comidas mezcladas','Sopas completas'],
      needs:['Elige por apariencia, textura y presentación — no por sabor','Prefiere la proteína servida sola','En sopas come solo carne, pollo y papa; deja el caldo','Cuando está enfermo solo toma jugos'], body:{}, tipoCuerpo:'—' },
    { id:'cris', name:'Christopher', role:'4 años', age:4, weight:15, hMin:14, hMax:22, color:'#BE9E2E',
      portions:{ kcal:1400, protein:'19 g', carbs:'175 g', fat:'45 g', fiber:'25 g', fruit:'1–1.5 tazas', veg:'1.5 tazas', dairy:'2.5 tazas', water:'1.7 L' },
      likes:['Jamón de pavo','Jamón con huevo','Carne guisada','Pollo','Lentejas con arroz (con ayuda)','Brócoli','Fresas','Mango','Leche con chocolate'],
      dislikes:['Arroz','Arepas','Carbohidratos (los deja)','Porciones grandes'],
      needs:['Se distrae mucho — come mejor con supervisión y ayuda','Termina primero la proteína y deja los carbohidratos','Come solo con finger foods: empanadas, snacks, cereal','Le encanta el chocolate — moderar'], body:{}, tipoCuerpo:'—' },
    { id:'rachel', name:'Rachel', role:'1 año', age:1, weight:8.6, hMin:8, hMax:12, color:'#A65A86',
      portions:{ kcal:900, protein:'13 g', carbs:'130 g', fat:'30 g', fiber:'19 g', fruit:'1 taza', veg:'¾ taza', dairy:'2 tazas', water:'1.3 L' },
      likes:['Mango','Aguacate','Tomate','Frijoles','Jamón','Mortadela','Huevo','Queso','Arepas','Comidas familiares'], dislikes:[],
      needs:['La más adaptable — come muy parecido a los adultos','Con algunas carnes mastica y escupe fibras (normal a su edad)','Texturas adecuadas y cortes seguros','Menos sal y condimentos'], body:{}, tipoCuerpo:'—' },
  ],

  // ---------- catálogo de comidas ----------
  desayunos: [
    {id:'d_perico',name:'Arepa con perico',tipo:'huevo',sides:'Aguacate · Papaya'},
    {id:'d_reina',name:'Arepa reina pepiada',tipo:'pollo',sides:'Aguacate · Fruta'},
    {id:'d_rellenas',name:'Arepas rellenas',tipo:'queso',sides:'Jamón · Pollo · Fruta'},
    {id:'d_cachapas',name:'Cachapas',tipo:'queso',sides:'Queso de mano · Fruta'},
    {id:'d_empanadas',name:'Empanadas venezolanas',tipo:'res',sides:'Salsa de ajo · Fruta'},
    {id:'d_mandocas',name:'Mandocas',tipo:'queso',sides:'Yogur · Fruta'},
    {id:'d_pan_perico',name:'Pan con perico',tipo:'huevo',sides:'Melón · Sandía'},
    {id:'d_tostadas',name:'Tostadas con aguacate',tipo:'huevo',sides:'Queso crema · Fruta'},
    {id:'d_canilla',name:'Pan canilla con queso',tipo:'queso',sides:'Fruta · Yogur'},
    {id:'d_tortilla',name:'Tortilla venezolana',tipo:'huevo',sides:'Arepa pequeña · Fruta'},
    {id:'d_domino',name:'Arepa dominó',tipo:'legumbre',sides:'Caraotas · Queso · Aguacate'},
    {id:'d_sifrina',name:'Arepa sifrina',tipo:'pollo',sides:'Aguacate · Queso amarillo'},
    {id:'d_pelua',name:'Arepa pelúa',tipo:'res',sides:'Carne mechada · Queso'},
    {id:'d_avena',name:'Avena venezolana',tipo:'lacteo',sides:'Pan · Queso · Fruta'},
    {id:'d_panquecas',name:'Panquecas',tipo:'dulce',sides:'Fruta · Miel · Yogur'},
  ],
  meriendas: [
    {id:'s_yogurt',name:'Yogurt de fresa',tipo:'lacteo',sides:'Banano · Granola'},
    {id:'s_cereal',name:'Cereal con leche',tipo:'lacteo',sides:'Banano o fresas'},
    {id:'s_fruta',name:'Fruta fresca',tipo:'fruta',sides:'Mango · Melón · Uvas'},
    {id:'s_queque',name:'Queque seco',tipo:'dulce',sides:'Leche o yogur'},
    {id:'s_avena',name:'Avena cocida',tipo:'lacteo',sides:'Banano · Canela'},
    {id:'s_arroz_leche',name:'Arroz con leche',tipo:'dulce',sides:'Canela · Manzana'},
    {id:'s_gelatina',name:'Gelatina con fruta',tipo:'dulce',sides:'Fresa · Kiwi · Uvas'},
    {id:'s_brownies',name:'Brownies caseros',tipo:'dulce',sides:'Leche o yogur'},
    {id:'s_churchill',name:'Churchill casero',tipo:'dulce',sides:'Helado · Frutas'},
    {id:'s_batido',name:'Batido de frutas',tipo:'fruta',sides:'Banano + fresa'},
    {id:'s_queso_uvas',name:'Queso en cubitos con uvas',tipo:'queso',sides:'Con proteína'},
    {id:'s_huevo',name:'Huevo sancochado',tipo:'huevo',sides:'Con proteína'},
    {id:'s_mini_arepa',name:'Mini arepa con queso',tipo:'queso',sides:'Con proteína'},
    {id:'s_sandwich',name:'Sándwich de jamón y queso',tipo:'queso',sides:'Pequeño · proteína'},
  ],
  almuerzos: [
    {id:'l_pollo_horno',name:'Pollo al horno',tipo:'pollo',sides:'Yuca · Arroz · Ensalada'},
    {id:'l_pollo_guisado',name:'Pollo guisado',tipo:'pollo',sides:'Papas · Arroz · Maduro'},
    {id:'l_arroz_pollo',name:'Arroz con pollo',tipo:'pollo',sides:'Patacones · Ensalada'},
    {id:'l_fajitas_pollo',name:'Fajitas de pollo',tipo:'pollo',sides:'Arroz · Maduro · Ensalada'},
    {id:'l_pasta_carne',name:'Pasta con carne',tipo:'res',sides:'Pan de ajo · Ensalada'},
    {id:'l_albondigas',name:'Albóndigas con pasta',tipo:'res',sides:'Maduro · Ensalada'},
    {id:'l_carne_salsa',name:'Carne en salsa',tipo:'res',sides:'Papas · Maduro · Ensalada'},
    {id:'l_carne_mechada',name:'Carne mechada',tipo:'res',sides:'Maduro · Ensalada'},
    {id:'l_bistec',name:'Bistec con vegetales',tipo:'res',sides:'Arroz · Maduro · Ensalada'},
    {id:'l_chuleta',name:'Chuleta de cerdo encebollada',tipo:'cerdo',sides:'Arroz · Ensalada'},
    {id:'l_trocitos',name:'Trocitos de cerdo',tipo:'cerdo',sides:'Arroz · Papas · Maduro'},
    {id:'l_cerdo_papas',name:'Cerdo con papas',tipo:'cerdo',sides:'Maduro · Ensalada'},
    {id:'l_costillas',name:'Costillas BBQ',tipo:'cerdo',sides:'Maduro · Ensalada'},
    {id:'l_pabellon',name:'Pabellón',tipo:'res',sides:'Arroz · Tajadas · Ensalada'},
    {id:'l_pescado',name:'Pescado empanizado',tipo:'pescado',sides:'Arroz · Patacones · Ensalada'},
    {id:'l_lentejas',name:'Sopa de lentejas',tipo:'legumbre',sides:'Arroz · Maduro · Ensalada'},
    {id:'l_arroz_arreglado',name:'Arroz arreglado',tipo:'pollo',sides:'Maduro · Ensalada'},
    {id:'l_pollo_blanca',name:'Pollo en salsa blanca',tipo:'pollo',sides:'Champiñones · Vegetales'},
    {id:'l_pollo_emp',name:'Pollo empanizado',tipo:'pollo',sides:'Ensalada · Pan de ajo'},
    {id:'l_wraps',name:'Wraps',tipo:'mixto',sides:'Papas'},
    {id:'l_club',name:'Club House',tipo:'mixto',sides:'Papas fritas · Ensalada'},
    {id:'l_pepito',name:'Pepito de pollo',tipo:'pollo',sides:'Papas'},
    {id:'l_sandwich_pollo',name:'Sándwich de pollo',tipo:'pollo',sides:'Papas fritas'},
    {id:'l_choripan',name:'Choripán',tipo:'cerdo',sides:'Papas'},
    {id:'l_hamburguesa',name:'Hamburguesa',tipo:'res',sides:'Papas'},
    {id:'l_fajitas_mix',name:'Fajitas mixtas',tipo:'mixto',sides:'Papas · Ensalada'},
    {id:'l_lasana',name:'Lasaña',tipo:'res',sides:'Pan de ajo · Ensalada'},
  ],
  cenas: [
    {id:'c_arepas',name:'Arepas de cena',tipo:'queso',sides:'Aguacate · Ensalada'},
    {id:'c_pabellon',name:'Pabellón criollo',tipo:'res',sides:'Arroz · Tajadas'},
    {id:'c_cachapas',name:'Cachapas con queso',tipo:'queso',sides:'Cerdo · Ensalada'},
    {id:'c_asado',name:'Asado negro',tipo:'res',sides:'Arroz · Ensalada'},
    {id:'c_pollo_guisado',name:'Pollo guisado',tipo:'pollo',sides:'Arroz · Ensalada · Maduro'},
    {id:'c_carne_mechada',name:'Carne mechada',tipo:'res',sides:'Arepa · Ensalada'},
    {id:'c_pasticho',name:'Pasticho',tipo:'res',sides:'Ensalada'},
    {id:'c_sopa_res',name:'Sopa de res',tipo:'res',sides:'Yuca · Papa · Zanahoria'},
    {id:'c_sancocho',name:'Sancocho de pollo',tipo:'pollo',sides:'Yuca · Elote · Plátano'},
    {id:'c_hallacas',name:'Hallacas (temporada)',tipo:'mixto',sides:'Ensalada de gallina'},
    {id:'c_empanadas',name:'Empanadas de cena',tipo:'res',sides:'Ensalada'},
    {id:'c_tostones',name:'Tostones con carne mechada',tipo:'res',sides:'Ensalada de repollo'},
    {id:'c_arroz_chino',name:'Arroz chino venezolano',tipo:'mixto',sides:'Vegetales salteados'},
    {id:'c_arepa_pizza',name:'Arepa pizza',tipo:'queso',sides:'Ensalada'},
    {id:'c_parrilla',name:'Parrilla familiar',tipo:'mixto',sides:'Yuca · Ensalada · Maduro'},
  ],

  // ---------- plan de comidas inicial ----------
  defaultPlan: {
    'Lun-desayuno':'d_perico','Lun-m1':'s_fruta','Lun-almuerzo':'l_pollo_horno','Lun-m2':'s_yogurt','Lun-cena':'c_arepas',
    'Mar-desayuno':'d_panquecas','Mar-m1':'s_yogurt','Mar-almuerzo':'l_pasta_carne','Mar-m2':'s_queque','Mar-cena':'c_pollo_guisado',
    'Mié-desayuno':'d_cachapas','Mié-m1':'s_batido','Mié-almuerzo':'l_pabellon','Mié-m2':'s_gelatina','Mié-cena':'c_sopa_res',
    'Jue-desayuno':'d_reina','Jue-m1':'s_queso_uvas','Jue-almuerzo':'l_pollo_guisado','Jue-m2':'s_avena','Jue-cena':'c_pabellon',
    'Vie-desayuno':'d_tostadas','Vie-m1':'s_fruta','Vie-almuerzo':'l_pescado','Vie-m2':'s_brownies','Vie-cena':'c_cachapas',
    'Sáb-desayuno':'d_empanadas','Sáb-m1':'s_cereal','Sáb-almuerzo':'l_costillas','Sáb-m2':'s_arroz_leche','Sáb-cena':'c_parrilla',
    'Dom-desayuno':'d_pan_perico','Dom-m1':'s_mini_arepa','Dom-almuerzo':'l_bistec','Dom-m2':'s_churchill','Dom-cena':'c_sancocho',
  },

  // ---------- inventario ----------
  inventory: [
    {id:'p1',name:'Sandía',cat:'Frutas',qty:'½ u',price:'—',status:'por acabarse'},
    {id:'p2',name:'Melón',cat:'Frutas',qty:'1 u',price:'—',status:'por acabarse'},
    {id:'p3',name:'Guayaba',cat:'Frutas',qty:'3 u',price:'—',status:'lleno'},
    {id:'p4',name:'Mango',cat:'Frutas',qty:'1.5 kg',price:'₡1.900 /kg',status:'lleno'},
    {id:'p5',name:'Durazno',cat:'Frutas',qty:'1 kg',price:'—',status:'lleno'},
    {id:'p6',name:'Fresas',cat:'Frutas',qty:'800 g',price:'₡2.400 /kg',status:'agotado'},
    {id:'p7',name:'Mandarina',cat:'Frutas',qty:'2 kg',price:'—',status:'lleno'},
    {id:'p8',name:'Naranja',cat:'Frutas',qty:'2 kg',price:'—',status:'lleno'},
    {id:'p9',name:'Piña',cat:'Frutas',qty:'1 u',price:'—',status:'por acabarse'},
    {id:'p10',name:'Banano',cat:'Frutas',qty:'2 kg',price:'₡900 /kg',status:'por acabarse'},
    {id:'p11',name:'Kiwi',cat:'Frutas',qty:'500 g',price:'—',status:'lleno'},
    {id:'p12',name:'Mamón chino',cat:'Frutas',qty:'1 kg',price:'—',status:'lleno'},
    {id:'p13',name:'Manzana',cat:'Frutas',qty:'1.5 kg',price:'—',status:'lleno'},
    {id:'p14',name:'Melocotón',cat:'Frutas',qty:'2 latas',price:'—',status:'lleno'},
    {id:'p15',name:'Limón',cat:'Frutas',qty:'1 kg',price:'—',status:'lleno'},
    {id:'p16',name:'Coco',cat:'Frutas',qty:'1 u',price:'—',status:'lleno'},
    {id:'p17',name:'Pera',cat:'Frutas',qty:'1 kg',price:'—',status:'lleno'},
    {id:'p18',name:'Papaya',cat:'Frutas',qty:'1 u',price:'—',status:'por acabarse'},
    {id:'p19',name:'Manzana verde',cat:'Frutas',qty:'1.5 kg',price:'—',status:'lleno'},
    {id:'p20',name:'Uva',cat:'Frutas',qty:'1 kg',price:'—',status:'lleno'},
    {id:'p21',name:'Maracuyá',cat:'Frutas',qty:'1 kg',price:'—',status:'lleno'},
    {id:'p22',name:'Cas',cat:'Frutas',qty:'500 g',price:'—',status:'lleno'},
    {id:'p23',name:'Limón mandarina',cat:'Frutas',qty:'1 kg',price:'—',status:'lleno'},
    {id:'p24',name:'Leche de coco',cat:'Frutas',qty:'2 latas',price:'—',status:'lleno'},
    {id:'p25',name:'Coco rallado',cat:'Frutas',qty:'500 g',price:'—',status:'lleno'},
    {id:'p26',name:'Lechuga',cat:'Verduras',qty:'2 u',price:'—',status:'por acabarse'},
    {id:'p27',name:'Tomate',cat:'Verduras',qty:'750 g',price:'₡1.400 /kg',status:'por acabarse'},
    {id:'p28',name:'Pepino',cat:'Verduras',qty:'500 g',price:'—',status:'lleno'},
    {id:'p29',name:'Repollo',cat:'Verduras',qty:'1 u',price:'—',status:'lleno'},
    {id:'p30',name:'Zanahoria',cat:'Verduras',qty:'1.2 kg',price:'—',status:'lleno'},
    {id:'p31',name:'Papa',cat:'Verduras',qty:'3 kg',price:'₡950 /kg',status:'lleno'},
    {id:'p32',name:'Remolacha',cat:'Verduras',qty:'1 kg',price:'—',status:'lleno'},
    {id:'p33',name:'Apio crudo',cat:'Verduras',qty:'500 g',price:'—',status:'lleno'},
    {id:'p34',name:'Hongos',cat:'Verduras',qty:'500 g',price:'—',status:'lleno'},
    {id:'p35',name:'Ayote (ayuma)',cat:'Verduras',qty:'1.5 kg',price:'—',status:'lleno'},
    {id:'p36',name:'Yuca',cat:'Verduras',qty:'2 kg',price:'—',status:'lleno'},
    {id:'p37',name:'Plátano',cat:'Verduras',qty:'8 u',price:'—',status:'lleno'},
    {id:'p38',name:'Cebolla morada',cat:'Verduras',qty:'1.5 kg',price:'—',status:'lleno'},
    {id:'p39',name:'Cebolla blanca',cat:'Verduras',qty:'1.5 kg',price:'—',status:'lleno'},
    {id:'p40',name:'Ajo',cat:'Verduras',qty:'200 g',price:'—',status:'lleno'},
    {id:'p41',name:'Chile dulce',cat:'Verduras',qty:'800 g',price:'—',status:'lleno'},
    {id:'p42',name:'Brócoli',cat:'Verduras',qty:'500 g',price:'—',status:'agotado'},
    {id:'p43',name:'Aguacate',cat:'Verduras',qty:'4 u',price:'—',status:'por acabarse'},
    {id:'p44',name:'Culantro',cat:'Verduras',qty:'3 manojos',price:'—',status:'por acabarse'},
    {id:'p45',name:'Culantro coyote',cat:'Verduras',qty:'3 manojos',price:'—',status:'por acabarse'},
    {id:'p46',name:'Culantro castilla',cat:'Verduras',qty:'3 manojos',price:'—',status:'por acabarse'},
    {id:'p47',name:'Culantro orejón',cat:'Verduras',qty:'3 manojos',price:'—',status:'por acabarse'},
    {id:'p48',name:'Cebollino',cat:'Verduras',qty:'3 manojos',price:'—',status:'por acabarse'},
    {id:'p49',name:'Elote',cat:'Verduras',qty:'4 u',price:'—',status:'lleno'},
    {id:'p50',name:'Maíz dulce',cat:'Verduras',qty:'4 latas',price:'—',status:'lleno'},
    {id:'p51',name:'Arroz blanco',cat:'Cereales',qty:'4 kg',price:'₡1.100 /kg',status:'lleno'},
    {id:'p52',name:'Arroz parbolizado',cat:'Cereales',qty:'1 kg',price:'—',status:'lleno'},
    {id:'p53',name:'Pasta tornillos',cat:'Cereales',qty:'2.5 kg',price:'—',status:'lleno'},
    {id:'p54',name:'Pasta',cat:'Cereales',qty:'2.5 kg',price:'—',status:'lleno'},
    {id:'p55',name:'Lentejas',cat:'Cereales',qty:'2.5 kg',price:'—',status:'lleno'},
    {id:'p56',name:'Frijoles rojos',cat:'Cereales',qty:'2.5 kg',price:'—',status:'lleno'},
    {id:'p57',name:'Frijoles negros',cat:'Cereales',qty:'2.5 kg',price:'—',status:'lleno'},
    {id:'p58',name:'Garbanzos',cat:'Cereales',qty:'2.5 kg',price:'—',status:'lleno'},
    {id:'p59',name:'Pan Altamura',cat:'Cereales',qty:'2 u',price:'—',status:'por acabarse'},
    {id:'p60',name:'Pan de sándwich',cat:'Cereales',qty:'1 pq',price:'—',status:'agotado'},
    {id:'p61',name:'Pan bonete',cat:'Cereales',qty:'1 promo',price:'—',status:'lleno'},
    {id:'p62',name:'Harina PAN',cat:'Cereales',qty:'2 kg',price:'—',status:'por acabarse'},
    {id:'p63',name:'Harina de trigo',cat:'Cereales',qty:'2 kg',price:'—',status:'lleno'},
    {id:'p64',name:'Harina para chapata',cat:'Cereales',qty:'2 kg',price:'—',status:'lleno'},
    {id:'p65',name:'Avena',cat:'Cereales',qty:'1.5 kg',price:'—',status:'lleno'},
    {id:'p66',name:'Cereal',cat:'Cereales',qty:'2 pq',price:'—',status:'lleno'},
    {id:'p67',name:'Queque seco',cat:'Cereales',qty:'1 u',price:'—',status:'lleno'},
    {id:'p68',name:'Galleta María',cat:'Cereales',qty:'2 pq',price:'—',status:'lleno'},
    {id:'p69',name:'Galleta de soda',cat:'Cereales',qty:'2 pq',price:'—',status:'lleno'},
    {id:'p70',name:'Granos de maíz',cat:'Cereales',qty:'2 pq',price:'—',status:'lleno'},
    {id:'p71',name:'Harina para panqueque',cat:'Cereales',qty:'1 pq',price:'—',status:'lleno'},
    {id:'p72',name:'Granola',cat:'Cereales',qty:'1 pq',price:'—',status:'lleno'},
    {id:'p73',name:'Baguette',cat:'Cereales',qty:'2 u',price:'—',status:'lleno'},
    {id:'p74',name:'Pollo entero',cat:'Proteína',qty:'4 kg',price:'₡2.200 /kg',status:'lleno'},
    {id:'p75',name:'Pechuga de pollo',cat:'Proteína',qty:'4 kg',price:'₡3.400 /kg',status:'lleno'},
    {id:'p76',name:'Muslo de pollo',cat:'Proteína',qty:'4 kg',price:'—',status:'lleno'},
    {id:'p77',name:'Filete de pollo',cat:'Proteína',qty:'4 kg',price:'—',status:'lleno'},
    {id:'p78',name:'Bistec',cat:'Proteína',qty:'2.5 kg',price:'—',status:'lleno'},
    {id:'p79',name:'Carne para mechar',cat:'Proteína',qty:'2.5 kg',price:'—',status:'lleno'},
    {id:'p80',name:'Carne molida',cat:'Proteína',qty:'2.5 kg',price:'₡4.200 /kg',status:'por acabarse'},
    {id:'p81',name:'Costilla de res',cat:'Proteína',qty:'2.5 kg',price:'—',status:'lleno'},
    {id:'p82',name:'Carne para sopa',cat:'Proteína',qty:'2.5 kg',price:'—',status:'lleno'},
    {id:'p83',name:'Chuleta de cerdo',cat:'Proteína',qty:'2.5 kg',price:'—',status:'lleno'},
    {id:'p84',name:'Costilla de cerdo',cat:'Proteína',qty:'2.5 kg',price:'—',status:'lleno'},
    {id:'p85',name:'Costilla ahumada',cat:'Proteína',qty:'1 kg',price:'—',status:'lleno'},
    {id:'p86',name:'Chuleta ahumada',cat:'Proteína',qty:'1 kg',price:'—',status:'lleno'},
    {id:'p87',name:'Trocitos de cerdo',cat:'Proteína',qty:'2.5 kg',price:'—',status:'lleno'},
    {id:'p88',name:'Tilapia',cat:'Proteína',qty:'1.5 kg',price:'—',status:'lleno'},
    {id:'p89',name:'Atún en agua',cat:'Proteína',qty:'6 latas',price:'—',status:'lleno'},
    {id:'p90',name:'Sardina en lata',cat:'Proteína',qty:'4 latas',price:'—',status:'lleno'},
    {id:'p91',name:'Huevos',cat:'Proteína',qty:'30 u',price:'₡3.600 /30',status:'por acabarse',priority:true},
    {id:'p92',name:'Salchichón',cat:'Proteína',qty:'1 kg',price:'—',status:'lleno'},
    {id:'p93',name:'Chorizo',cat:'Proteína',qty:'1 kg',price:'—',status:'lleno'},
    {id:'p94',name:'Jamón',cat:'Proteína',qty:'1 kg',price:'—',status:'lleno'},
    {id:'p95',name:'Salchicha',cat:'Proteína',qty:'1 kg',price:'—',status:'lleno'},
    {id:'p96',name:'Yogurt',cat:'Lácteos',qty:'1 L',price:'—',status:'por acabarse'},
    {id:'p97',name:'Queso semiduro',cat:'Lácteos',qty:'1 kg',price:'₡4.800 /kg',status:'lleno'},
    {id:'p98',name:'Queso San Carlos',cat:'Lácteos',qty:'1 kg',price:'—',status:'agotado'},
    {id:'p99',name:'Queso crema',cat:'Lácteos',qty:'1 L',price:'—',status:'lleno'},
    {id:'p100',name:'Natilla',cat:'Lácteos',qty:'1 L',price:'—',status:'lleno'},
    {id:'p101',name:'Leche líquida',cat:'Lácteos',qty:'4 L',price:'₡1.150 /L',status:'por acabarse'},
    {id:'p102',name:'Leche en polvo',cat:'Lácteos',qty:'900 g',price:'—',status:'lleno'},
    {id:'p103',name:'Leche condensada',cat:'Lácteos',qty:'6 latas',price:'—',status:'lleno'},
    {id:'p104',name:'Mantequilla',cat:'Lácteos',qty:'500 g',price:'—',status:'por acabarse'},
    {id:'p105',name:'Mantequilla de ajo',cat:'Lácteos',qty:'1 frasco',price:'—',status:'por acabarse'},
    {id:'p106',name:'Aceite',cat:'Grasas',qty:'1 L',price:'—',status:'lleno'},
    {id:'p107',name:'Mayonesa',cat:'Grasas',qty:'1 frasco',price:'—',status:'lleno'},
    {id:'p108',name:'Nuez',cat:'Grasas',qty:'500 g',price:'—',status:'lleno'},
    {id:'p109',name:'Almendra',cat:'Grasas',qty:'500 g',price:'—',status:'lleno'},
    {id:'p110',name:'Maní',cat:'Grasas',qty:'500 g',price:'—',status:'lleno'},
    {id:'p111',name:'Maní japonés',cat:'Grasas',qty:'500 g',price:'—',status:'lleno'},
    {id:'p112',name:'Mantequilla de maní',cat:'Grasas',qty:'1 frasco',price:'—',status:'lleno'},
    {id:'p113',name:'Marañón',cat:'Grasas',qty:'500 g',price:'—',status:'lleno'},
    {id:'p114',name:'Mantequilla líquida',cat:'Grasas',qty:'500 g',price:'—',status:'lleno'},
    {id:'p115',name:'Tapa dulce',cat:'Azúcar y dulces',qty:'1 kg',price:'—',status:'lleno'},
    {id:'p116',name:'Azúcar',cat:'Azúcar y dulces',qty:'1 kg',price:'—',status:'lleno'},
    {id:'p117',name:'Nutella',cat:'Azúcar y dulces',qty:'1 frasco',price:'—',status:'lleno'},
    {id:'p118',name:'Gelatina',cat:'Azúcar y dulces',qty:'4 sobres',price:'—',status:'lleno'},
    {id:'p119',name:'Mermelada',cat:'Azúcar y dulces',qty:'1 frasco',price:'—',status:'lleno'},
    {id:'p120',name:'Miel',cat:'Azúcar y dulces',qty:'1 frasco',price:'—',status:'lleno'},
    {id:'p121',name:'Jarabe para panqueques',cat:'Azúcar y dulces',qty:'1 frasco',price:'—',status:'lleno'},
    {id:'p122',name:'Galletas',cat:'Azúcar y dulces',qty:'4 pq',price:'—',status:'lleno'},
    {id:'p123',name:'Doritos',cat:'Azúcar y dulces',qty:'1 pq',price:'—',status:'lleno'},
    {id:'p124',name:'Dulce de leche',cat:'Azúcar y dulces',qty:'2 latas',price:'—',status:'lleno'},
    {id:'p125',name:'Sal',cat:'Condimentos',qty:'1 kg',price:'—',status:'lleno'},
    {id:'p126',name:'Pimienta negra',cat:'Condimentos',qty:'50 g',price:'—',status:'lleno'},
    {id:'p127',name:'Orégano',cat:'Condimentos',qty:'50 g',price:'—',status:'lleno'},
    {id:'p128',name:'Comino',cat:'Condimentos',qty:'50 g',price:'—',status:'lleno'},
    {id:'p129',name:'Curry',cat:'Condimentos',qty:'50 g',price:'—',status:'lleno'},
    {id:'p130',name:'Achiote',cat:'Condimentos',qty:'1 frasco',price:'—',status:'lleno'},
    {id:'p131',name:'Sobres de olla de carne',cat:'Condimentos',qty:'4 u',price:'—',status:'por acabarse'},
    {id:'p132',name:'Condimentos en polvo',cat:'Condimentos',qty:'1 frasco',price:'—',status:'lleno'},
    {id:'p133',name:'Vinagre',cat:'Condimentos',qty:'1 frasco',price:'—',status:'lleno'},
    {id:'p134',name:'Canela',cat:'Condimentos',qty:'50 g',price:'—',status:'lleno'},
    {id:'p135',name:'Salsa inglesa',cat:'Salsas',qty:'1 frasco',price:'—',status:'lleno'},
    {id:'p136',name:'Salsa de ajo',cat:'Salsas',qty:'1 frasco',price:'—',status:'por acabarse'},
    {id:'p137',name:'Salsa de soya',cat:'Salsas',qty:'1 frasco',price:'—',status:'por acabarse'},
    {id:'p138',name:'Salsa de tomate',cat:'Salsas',qty:'1 frasco',price:'—',status:'lleno'},
    {id:'p139',name:'Salsa BBQ',cat:'Salsas',qty:'1 frasco',price:'—',status:'lleno'},
    {id:'p140',name:'Mostaza',cat:'Salsas',qty:'1 frasco',price:'—',status:'lleno'},
    {id:'p141',name:'Vainilla',cat:'Salsas',qty:'1 frasco',price:'—',status:'lleno'},
    {id:'p142',name:'Detergente para ropa',cat:'Limpieza',qty:'1 bolsa',price:'₡5.500',status:'agotado',priority:true},
    {id:'p143',name:'Detergente para platos',cat:'Limpieza',qty:'1 botella',price:'—',status:'por acabarse',priority:true},
    {id:'p144',name:'Desinfectante',cat:'Limpieza',qty:'1 botella',price:'—',status:'por acabarse',priority:true},
    {id:'p145',name:'Bolsas de basura',cat:'Limpieza',qty:'1 rollo',price:'—',status:'por acabarse',priority:true},
    {id:'p146',name:'Paños de microfibra',cat:'Limpieza',qty:'0',price:'—',status:'agotado',priority:true},
    {id:'p147',name:'Esponjas',cat:'Limpieza',qty:'2',price:'—',status:'por acabarse',priority:true},
    {id:'p148',name:'Gel para cucarachas',cat:'Limpieza',qty:'0',price:'—',status:'agotado',priority:true},
    {id:'p149',name:'Trampas para cucarachas',cat:'Limpieza',qty:'0',price:'—',status:'agotado',priority:true},
    {id:'p150',name:'Cloro',cat:'Limpieza',qty:'1 botella',price:'—',status:'lleno'},
    {id:'p151',name:'Pasta dental',cat:'Higiene',qty:'1 tubo',price:'—',status:'por acabarse',priority:true},
    {id:'p152',name:'Shampoo',cat:'Higiene',qty:'1 botella',price:'—',status:'por acabarse',priority:true},
    {id:'p153',name:'Jabón de manos',cat:'Higiene',qty:'0',price:'—',status:'agotado',priority:true},
    {id:'p154',name:'Papel higiénico',cat:'Higiene',qty:'4 rollos',price:'₡3.200 /12',status:'por acabarse',priority:true},
    {id:'p155',name:'Desodorante',cat:'Higiene',qty:'2',price:'—',status:'lleno'},
    {id:'p156',name:'Cepillos dentales',cat:'Higiene',qty:'4',price:'—',status:'lleno'},
    {id:'p157',name:'Pañales',cat:'Bebé',qty:'0',price:'₡8.900 /pq',status:'agotado',priority:true},
    {id:'p158',name:'Toallas húmedas',cat:'Bebé',qty:'1 pq',price:'—',status:'por acabarse',priority:true},
    {id:'p159',name:'Crema para rozaduras',cat:'Bebé',qty:'0',price:'—',status:'agotado',priority:true},
    {id:'p160',name:'Shampoo para bebé',cat:'Bebé',qty:'1 botella',price:'—',status:'lleno'},
    {id:'p161',name:'Jabón para bebé',cat:'Bebé',qty:'1',price:'—',status:'lleno'},
  ],

  // ---------- compra quincenal ----------
  quincenalData: [
    {id:'prot', name:'Proteínas animales', unit:'kg', color:'#9C3A52', min:40, max:50, items:[
      {name:'Pollo entero',unit:'kg',step:0.5,kgPer:1,def:4},{name:'Pechuga de pollo',unit:'kg',step:0.5,kgPer:1,def:4},
      {name:'Muslo de pollo',unit:'kg',step:0.5,kgPer:1,def:4},{name:'Filete de pollo',unit:'kg',step:0.5,kgPer:1,def:4},
      {name:'Bistec',unit:'kg',step:0.5,kgPer:1,def:2.5},{name:'Carne para mechar',unit:'kg',step:0.5,kgPer:1,def:2.5},
      {name:'Carne molida',unit:'kg',step:0.5,kgPer:1,def:2.5},{name:'Costilla de res',unit:'kg',step:0.5,kgPer:1,def:2.5},
      {name:'Carne para sopa',unit:'kg',step:0.5,kgPer:1,def:2.5},{name:'Chuleta de cerdo',unit:'kg',step:0.5,kgPer:1,def:2.5},
      {name:'Costilla de cerdo',unit:'kg',step:0.5,kgPer:1,def:2.5},{name:'Trocitos de cerdo',unit:'kg',step:0.5,kgPer:1,def:2.5},
      {name:'Tilapia',unit:'kg',step:0.5,kgPer:1,def:1.5},{name:'Huevos',unit:'u',step:6,kgPer:0.06,def:30},
      {name:'Jamón',unit:'kg',step:0.25,kgPer:1,def:1},{name:'Chorizo',unit:'kg',step:0.25,kgPer:1,def:0.5},
      {name:'Salchichón',unit:'kg',step:0.25,kgPer:1,def:0.5},
    ]},
    {id:'granos', name:'Granos y cereales', unit:'kg', color:'#9C7C45', min:19, max:27, items:[
      {name:'Arroz blanco',unit:'kg',step:0.5,kgPer:1,def:4},{name:'Arroz parbolizado',unit:'kg',step:0.5,kgPer:1,def:1},
      {name:'Pasta tornillos',unit:'kg',step:0.5,kgPer:1,def:2.5},{name:'Pasta',unit:'kg',step:0.5,kgPer:1,def:2.5},
      {name:'Lentejas',unit:'kg',step:0.5,kgPer:1,def:2.5},{name:'Frijoles rojos',unit:'kg',step:0.5,kgPer:1,def:2.5},
      {name:'Frijoles negros',unit:'kg',step:0.5,kgPer:1,def:2.5},{name:'Garbanzos',unit:'kg',step:0.5,kgPer:1,def:2.5},
      {name:'Avena',unit:'kg',step:0.5,kgPer:1,def:1.5},
    ]},
    {id:'harinas', name:'Harinas y panes', unit:'kg', color:'#B89A52', min:9, max:13, items:[
      {name:'Harina PAN',unit:'kg',step:0.5,kgPer:1,def:2},{name:'Harina de trigo',unit:'kg',step:0.5,kgPer:1,def:2},
      {name:'Harina para chapata',unit:'kg',step:0.5,kgPer:1,def:2},{name:'Pan Altamura',unit:'u',step:1,kgPer:0.5,def:2},
      {name:'Pan de sándwich',unit:'u',step:1,kgPer:0.6,def:1},{name:'Baguette',unit:'u',step:1,kgPer:0.25,def:2},
      {name:'Galleta María',unit:'pq',step:1,kgPer:0.2,def:2},{name:'Cereal',unit:'pq',step:1,kgPer:0.4,def:2},
    ]},
    {id:'tuberc', name:'Tubérculos y plátanos', unit:'kg', color:'#7C6A48', min:14, max:19, items:[
      {name:'Papa',unit:'kg',step:0.5,kgPer:1,def:4},{name:'Yuca',unit:'kg',step:0.5,kgPer:1,def:3},
      {name:'Auyama',unit:'kg',step:0.5,kgPer:1,def:2},{name:'Camote',unit:'kg',step:0.5,kgPer:1,def:2},
      {name:'Plátano',unit:'u',step:1,kgPer:0.2,def:12},{name:'Elote',unit:'u',step:1,kgPer:0.25,def:4},
    ]},
    {id:'frutas', name:'Frutas', unit:'kg', color:'#A6415C', min:26, max:35, items:[
      {name:'Sandía',unit:'kg',step:0.5,kgPer:1,def:4},{name:'Melón',unit:'kg',step:0.5,kgPer:1,def:3},
      {name:'Mango',unit:'kg',step:0.5,kgPer:1,def:1.5},{name:'Banano',unit:'kg',step:0.5,kgPer:1,def:2},
      {name:'Manzana',unit:'kg',step:0.5,kgPer:1,def:1.5},{name:'Mandarina',unit:'kg',step:0.5,kgPer:1,def:2},
      {name:'Naranja',unit:'kg',step:0.5,kgPer:1,def:2},{name:'Piña',unit:'kg',step:0.5,kgPer:1,def:2},
      {name:'Fresas',unit:'kg',step:0.25,kgPer:1,def:0.8},{name:'Uva',unit:'kg',step:0.25,kgPer:1,def:1},
      {name:'Papaya',unit:'kg',step:0.5,kgPer:1,def:2},{name:'Pera',unit:'kg',step:0.5,kgPer:1,def:1},
      {name:'Kiwi',unit:'kg',step:0.25,kgPer:1,def:0.5},{name:'Durazno',unit:'kg',step:0.5,kgPer:1,def:1},
      {name:'Guayaba',unit:'kg',step:0.25,kgPer:1,def:0.8},{name:'Maracuyá',unit:'kg',step:0.25,kgPer:1,def:1},
      {name:'Mamón chino',unit:'kg',step:0.25,kgPer:1,def:1},
    ]},
    {id:'verduras', name:'Verduras', unit:'kg', color:'#0F7A63', min:23, max:32, items:[
      {name:'Tomate',unit:'kg',step:0.25,kgPer:1,def:2},{name:'Cebolla',unit:'kg',step:0.5,kgPer:1,def:3},
      {name:'Zanahoria',unit:'kg',step:0.5,kgPer:1,def:3},{name:'Repollo',unit:'kg',step:0.5,kgPer:1,def:2},
      {name:'Remolacha',unit:'kg',step:0.5,kgPer:1,def:2},{name:'Pepino',unit:'kg',step:0.5,kgPer:1,def:2},
      {name:'Chile dulce',unit:'kg',step:0.25,kgPer:1,def:2},{name:'Brócoli',unit:'kg',step:0.25,kgPer:1,def:1.5},
      {name:'Lechuga',unit:'kg',step:0.5,kgPer:1,def:2},{name:'Aguacate',unit:'kg',step:0.5,kgPer:1,def:2},
      {name:'Apio',unit:'kg',step:0.25,kgPer:1,def:1.5},{name:'Hongos',unit:'kg',step:0.25,kgPer:1,def:1},
      {name:'Vainica',unit:'kg',step:0.25,kgPer:1,def:1},{name:'Coliflor',unit:'kg',step:0.5,kgPer:1,def:1},
      {name:'Espinaca',unit:'kg',step:0.25,kgPer:1,def:1},
    ]},
    {id:'quesos', name:'Quesos', unit:'kg', color:'#BE9E2E', min:4, max:5, items:[
      {name:'Queso semiduro',unit:'kg',step:0.25,kgPer:1,def:1.5},{name:'Queso San Carlos',unit:'kg',step:0.25,kgPer:1,def:1},
      {name:'Queso de mano',unit:'kg',step:0.25,kgPer:1,def:1},{name:'Queso crema',unit:'kg',step:0.25,kgPer:1,def:1},
    ]},
    {id:'leche', name:'Leche y yogurt', unit:'L', color:'#2E6FB0', min:24, max:33, items:[
      {name:'Leche',unit:'L',step:1,kgPer:1,def:20},{name:'Yogurt',unit:'L',step:0.5,kgPer:1,def:6},
      {name:'Natilla',unit:'L',step:0.5,kgPer:1,def:2},
    ]},
    {id:'grasas', name:'Grasas saludables', unit:'kg/L', color:'#4F7A6A', min:5, max:8, items:[
      {name:'Aceite',unit:'L',step:0.5,kgPer:1,def:1},{name:'Mantequilla',unit:'kg',step:0.25,kgPer:1,def:0.5},
      {name:'Mantequilla de maní',unit:'kg',step:0.25,kgPer:1,def:0.5},{name:'Maní',unit:'kg',step:0.25,kgPer:1,def:0.5},
      {name:'Almendra',unit:'kg',step:0.25,kgPer:1,def:0.5},{name:'Nuez',unit:'kg',step:0.25,kgPer:1,def:0.5},
      {name:'Marañón',unit:'kg',step:0.25,kgPer:1,def:0.5},{name:'Mayonesa',unit:'kg',step:0.25,kgPer:1,def:0.5},
      {name:'Mantequilla líquida',unit:'L',step:0.25,kgPer:1,def:0.5},{name:'Aguacate',unit:'kg',step:0.5,kgPer:1,def:1.5},
    ]},
  ],

  // ---------- frescura / orden de consumo ----------
  goldenWindows: [
    { day:'Día 1–3', tag:'Consumir ya', color:'#A32C54', items:['Ensaladas verdes','Fresas','Melón','Mango maduro','Lechuga','Culantro y cebollino','Sandía','Yogur abierto'] },
    { day:'Día 4–7', tag:'Media semana', color:'#C28A2A', items:['Pepino','Tomate maduro','Banano','Chile dulce','Jamón y mortadela abiertos','Quesos abiertos','Papaya','Piña'] },
    { day:'Día 8–15', tag:'Final de quincena', color:'#0F7A63', items:['Papa','Zanahoria','Camote','Ayote','Mandarina y manzana','Lentejas','Frijoles','Carnes congeladas','Harinas'] },
  ],
  miniMarket: ['Fresas','Lechuga','Culantro','Cebollino','Melón','Sandía','Mango maduro','Tomate','Pepino','Banano'],
  shelfTiers: [
    { label:'1–3 días', sub:'Consumir ya', color:'#A32C54', items:['Fresas maduras','Melón abierto','Sandía abierta','Mango muy maduro','Lechuga','Culantro coyote','Culantro castilla','Cebollino','Ensalada verde','Pico de gallo','Yogur abierto'] },
    { label:'3–7 días', sub:'Pronto', color:'#C2783A', items:['Mango medio maduro','Banano maduro','Papaya abierta','Piña abierta','Pepino','Tomate maduro','Chile dulce','Jamón de pavo abierto','Mortadela abierta','Queso rallado','Pollo descongelado'] },
    { label:'1–2 semanas', sub:'Sin prisa', color:'#BE9E2E', items:['Mandarina','Manzana','Pera','Zanahoria','Brócoli','Ayote abierto','Queso semiduro','Queso San Carlos','Queso sumidero','Cheddar','Huevos sancochados'] },
    { label:'2–4 semanas', sub:'Tubérculos y frescos resistentes', color:'#4F7A6A', items:['Papa','Camote','Yuca fresca','Plátano verde','Huevos frescos','Chorizo refrigerado'] },
    { label:'1–3 meses', sub:'Congelados', color:'#0F7A63', items:['Pollo','Costilla de cerdo','Posta de cerdo','Carne para sopa','Bistec','Carne molida'] },
    { label:'3–6 meses', sub:'Legumbres, harinas y cereales', color:'#2E6FB0', items:['Frijoles negros','Frijoles rojos','Lentejas','Harina de maíz','Harina de trigo','Avena'] },
    { label:'6–12 meses', sub:'Despensa seca', color:'#2D86C2', items:['Arroz','Pasta','Palomitas de maíz','Tang','Salsa de soya','Salsa Alfredo','Azúcar','Sal'] },
    { label:'1 año o más', sub:'Conservas', color:'#5E5A9E', items:['Leche condensada cerrada','Coco rallado seco','Condimentos secos','Sazonadores','Sobres de sopa'] },
  ],
  wasteRanking: [
    { rank:'1', name:'Lechuga', note:'Se daña en 1–3 días' },
    { rank:'2', name:'Fresas parcialmente maduras', note:'Maduran y se pasan rápido' },
    { rank:'3', name:'Melón', note:'Abierto: 1–2 días' },
    { rank:'4', name:'Papaya', note:'Se ablanda muy rápido' },
    { rank:'5', name:'Piña', note:'Fermenta al abrirse' },
    { rank:'6', name:'Yuca olvidada', note:'Se oxida y amarga' },
  ],

  // ---------- porciones / objetivos ----------
  plateGoals: {
    mantener: { desc:'Mantenimiento · plato equilibrado para conservar peso y energía.', plates:[
      {meal:'DESAYUNO', v:40, c:40, p:20}, {meal:'ALMUERZO', v:40, c:40, p:20}, {meal:'CENA', v:50, c:20, p:30},
    ]},
    perder: { desc:'Perder grasa · déficit moderado: más vegetales y proteína, menos carbohidratos.', plates:[
      {meal:'DESAYUNO', v:40, c:30, p:30}, {meal:'ALMUERZO', v:50, c:25, p:25}, {meal:'CENA', v:60, c:15, p:25},
    ]},
    ganar: { desc:'Ganar músculo · superávit moderado: más carbohidratos y proteína para construir músculo.', plates:[
      {meal:'DESAYUNO', v:30, c:40, p:30}, {meal:'ALMUERZO', v:30, c:40, p:30}, {meal:'CENA', v:40, c:20, p:40},
    ]},
  },
  goalLabels: { mantener:'Mantener', perder:'Perder grasa', ganar:'Ganar músculo' },
  bodyFields: [
    {key:'grasa',label:'Grasa corporal',unit:'%'},{key:'musculo',label:'Músculo',unit:'%'},
    {key:'agua',label:'Humedad / agua',unit:'%'},{key:'osea',label:'Masa ósea',unit:'kg'},
    {key:'bmr',label:'BMR',unit:'kcal'},{key:'tasaProteina',label:'Tasa de proteína',unit:'%'},
    {key:'edadCorporal',label:'Edad corporal',unit:'años'},{key:'visceral',label:'Grasa visceral',unit:'niv'},
    {key:'subcutanea',label:'Grasa subcutánea',unit:'%'},{key:'sinGrasa',label:'Peso sin grasa',unit:'kg'},
    {key:'pesoMuscular',label:'Peso muscular',unit:'kg'},{key:'proteinaG',label:'Proteína',unit:'g'},
    {key:'obesidad',label:'Grado de obesidad',unit:'%'},
  ],
  tipoCuerpoOpts: ['—','Oculto (delgado-graso)','Delgado','Delgado musculoso','Estándar','Estándar musculoso','Robusto','Robusto musculoso'],

  // ---------- presupuesto: categorías de gasto ----------
  presupuestoCats: ['Mercado / quincena','Vivienda','Servicios','Transporte','Salud','Educación','Higiene y limpieza','Bebé','Ocio','Otros'],

  // ---------- paletas ----------
  tipoColor: { pollo:'#C28A2A', res:'#A32C54', cerdo:'#A65A86', pescado:'#2E6FB0', legumbre:'#7C6A48', veggie:'#0F7A63', fruta:'#0F7A63', mixto:'#5E5A9E', queso:'#BE9E2E', huevo:'#C9A94A', lacteo:'#2E6FB0', dulce:'#9C7C45' },
  catColor: { Frutas:'#A32C54', Verduras:'#0F7A63', Cereales:'#9C7C45', 'Proteína':'#9C3A52', 'Lácteos':'#2E6FB0', Grasas:'#BE9E2E', 'Azúcar y dulces':'#C2783A', 'Condimentos':'#7C6A48', 'Salsas':'#A6415C', Despensa:'#6E6B50', Limpieza:'#2D86C2', 'Higiene':'#5E5A9E', 'Bebé':'#A65A86' },
  cats: ['Todos','Frutas','Verduras','Cereales','Proteína','Lácteos','Grasas','Azúcar y dulces','Condimentos','Salsas','Limpieza','Higiene','Bebé'],
  invFormCats: ['Frutas','Verduras','Cereales','Proteína','Lácteos','Grasas','Azúcar y dulces','Condimentos','Salsas','Limpieza','Higiene','Bebé'],
  days: [
    {k:'Lun',full:'Lunes'},{k:'Mar',full:'Martes'},{k:'Mié',full:'Miércoles'},
    {k:'Jue',full:'Jueves'},{k:'Vie',full:'Viernes'},{k:'Sáb',full:'Sábado'},{k:'Dom',full:'Domingo'}
  ],
  slots: [
    {k:'desayuno',l:'Desayuno',t:'desayuno'},{k:'m1',l:'Merienda AM',t:'merienda'},
    {k:'almuerzo',l:'Almuerzo',t:'almuerzo'},{k:'m2',l:'Merienda PM',t:'merienda'},
    {k:'cena',l:'Cena',t:'cena'}
  ],
};
